image: alpine/edge

oauth: pages.sr.ht/PAGES:RW

packages:
  - hut

environment:
  site: geff.xyz

tasks:
- package: |
    cd website
    tar -cvz . > ../site.tar.gz
- upload: |
    hut pages publish -d $site site.tar.gz
